### PR TITLE
issue-1006: Add compatibility with Django 5.2.0

### LINKED ISSUE #1006: DMR fails to work with `django==5.2`
### What's wrong?

The `MAX_URL_REDIRECT_LENGTH` variable defined in `django/utils/http.py` is missing in Django version 5.2.0

This causes the ImportError while trying to run DMR.

```
web-1      |   File "/usr/local/lib/python3.14/site-packages/dmr/response.py", line 9, in <module>
web-1      |     from django.utils.http import MAX_URL_REDIRECT_LENGTH
web-1      | ImportError: cannot import name 'MAX_URL_REDIRECT_LENGTH' from 'django.utils.http' (/usr/local/lib/python3.14/site-packages/django/utils/http.py)
``` 

### How it should be?

Be compatible with `django==5.2` which does not have such variable defined.

### Used versions

django-modern-rest==0.8.0
django==5.2.0

### OS information

Docker image `python:3.14-slim`

### PR DESCRIPTION
**Pull request by PashaWNN**
Handle ImportError for MAX_URL_REDIRECT_LENGTH for compatibility with Django 5.2.

# I have made things!

## AI Policy

- [x] I have read and agree to the [AI Policy](https://github.com/wemake-services/django-modern-rest/blob/master/.github/AI_POLICY.md), removed any "Co-Authored-By" lines attributing coding agents, and manually reviewed the final result

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
    - Not sure I shall make this type of tests by myself while implementing minor fix
- [x] I have updated the documentation for the changes I have made

## Related issues

- Closes #1006

### CODE REVIEW

File: dmr/response.py [hunk 1]
```diff
@@ -6,7 +6,11 @@
 from django.core.exceptions import DisallowedRedirect
 from django.http import HttpResponse
 from django.utils.encoding import iri_to_uri
-from django.utils.http import MAX_URL_REDIRECT_LENGTH
+
+try:
+    from django.utils.http import MAX_URL_REDIRECT_LENGTH
+except ImportError:
```
Comment (sobolevn) [inline dmr/response.py]:
```suggestion
except ImportError:  # pragma: no cover
```

File: dmr/response.py [hunk 2]
```diff
@@ -6,7 +6,11 @@
...
+    MAX_URL_REDIRECT_LENGTH = 16384  # Django 5.2 compat
```
Comment (sobolevn) [inline dmr/response.py]: It is the same as https://github.com/django/django/blob/21dcd9a94fb3e9edeec883d12cd1dcac5e773abe/django/utils/http.py#L42

**Review by sobolevn — APPROVED** [review]
Thanks!

File: dmr/response.py [hunk 3]
```diff
@@ -6,7 +6,11 @@
 from django.core.exceptions import DisallowedRedirect
 from django.http import HttpResponse
 from django.utils.encoding import iri_to_uri
-from django.utils.http import MAX_URL_REDIRECT_LENGTH
+
+try:
+    from django.utils.http import MAX_URL_REDIRECT_LENGTH
+except ImportError:  # pragma: no cover
+    MAX_URL_REDIRECT_LENGTH = 16384  # Django 5.2 compat
```
Comment (sobolevn) [inline dmr/response.py]:
```suggestion
    # Django 5.2.0 compat:
    MAX_URL_REDIRECT_LENGTH = 16384  # pyright: ignore[reportConstantRedefinition]
```
