### ISSUE TITLE
DMR fails to work with `django==5.2`

### ISSUE THREAD

**Issue by PashaWNN** [wemake-services/django-modern-rest#1006]
### What's wrong?

The `MAX_URL_REDIRECT_LENGTH` variable defined in `django/utils/http.py` is missing in Django version 5.2.0

This causes the ImportError while trying to run DMR.

```
web-1      |   File "/usr/local/lib/python3.14/site-packages/dmr/response.py", line 9, in <module>
web-1      |     from django.utils.http import MAX_URL_REDIRECT_LENGTH
web-1      | ImportError: cannot import name 'MAX_URL_REDIRECT_LENGTH' from 'django.utils.http' (/usr/local/lib/python3.14/site-packages/django/utils/http.py)
``` 

### How it should be?

Be compatible with `django==5.2` which does not have such variable defined.

### Used versions

django-modern-rest==0.8.0
django==5.2.0

### OS information

Docker image `python:3.14-slim`
